/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Proxy_constants.h"

namespace rdd { namespace proxy {

const ProxyConstants g_Proxy_constants;

ProxyConstants::ProxyConstants() {
}

}} // namespace

