/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Proxy_H
#define Proxy_H

#include <thrift/TDispatchProcessor.h>
#include "Proxy_types.h"

namespace rdd { namespace proxy {

class ProxyIf {
 public:
  virtual ~ProxyIf() {}
  virtual void run(Result& _return, const Query& query) = 0;
};

class ProxyIfFactory {
 public:
  typedef ProxyIf Handler;

  virtual ~ProxyIfFactory() {}

  virtual ProxyIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProxyIf* /* handler */) = 0;
};

class ProxyIfSingletonFactory : virtual public ProxyIfFactory {
 public:
  ProxyIfSingletonFactory(const boost::shared_ptr<ProxyIf>& iface) : iface_(iface) {}
  virtual ~ProxyIfSingletonFactory() {}

  virtual ProxyIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProxyIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProxyIf> iface_;
};

class ProxyNull : virtual public ProxyIf {
 public:
  virtual ~ProxyNull() {}
  void run(Result& /* _return */, const Query& /* query */) {
    return;
  }
};

typedef struct _Proxy_run_args__isset {
  _Proxy_run_args__isset() : query(false) {}
  bool query;
} _Proxy_run_args__isset;

class Proxy_run_args {
 public:

  Proxy_run_args() {
  }

  virtual ~Proxy_run_args() throw() {}

  Query query;

  _Proxy_run_args__isset __isset;

  void __set_query(const Query& val) {
    query = val;
  }

  bool operator == (const Proxy_run_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const Proxy_run_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxy_run_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Proxy_run_pargs {
 public:


  virtual ~Proxy_run_pargs() throw() {}

  const Query* query;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Proxy_run_result__isset {
  _Proxy_run_result__isset() : success(false) {}
  bool success;
} _Proxy_run_result__isset;

class Proxy_run_result {
 public:

  Proxy_run_result() {
  }

  virtual ~Proxy_run_result() throw() {}

  Result success;

  _Proxy_run_result__isset __isset;

  void __set_success(const Result& val) {
    success = val;
  }

  bool operator == (const Proxy_run_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Proxy_run_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Proxy_run_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Proxy_run_presult__isset {
  _Proxy_run_presult__isset() : success(false) {}
  bool success;
} _Proxy_run_presult__isset;

class Proxy_run_presult {
 public:


  virtual ~Proxy_run_presult() throw() {}

  Result* success;

  _Proxy_run_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ProxyClient : virtual public ProxyIf {
 public:
  ProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ProxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void run(Result& _return, const Query& query);
  void send_run(const Query& query);
  void recv_run(Result& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProxyProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProxyIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProxyProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_run(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProxyProcessor(boost::shared_ptr<ProxyIf> iface) :
    iface_(iface) {
    processMap_["run"] = &ProxyProcessor::process_run;
  }

  virtual ~ProxyProcessor() {}
};

class ProxyProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProxyProcessorFactory(const ::boost::shared_ptr< ProxyIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProxyIfFactory > handlerFactory_;
};

class ProxyMultiface : virtual public ProxyIf {
 public:
  ProxyMultiface(std::vector<boost::shared_ptr<ProxyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProxyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProxyIf> > ifaces_;
  ProxyMultiface() {}
  void add(boost::shared_ptr<ProxyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void run(Result& _return, const Query& query) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->run(_return, query);
    }
    ifaces_[i]->run(_return, query);
    return;
  }

};

}} // namespace

#endif
