/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Proxy_CONSTANTS_H
#define Proxy_CONSTANTS_H

#include "Proxy_types.h"

namespace rdd { namespace proxy {

class ProxyConstants {
 public:
  ProxyConstants();

};

extern const ProxyConstants g_Proxy_constants;

}} // namespace

#endif
