// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Scribe.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::rdd;

class ScribeHandler : virtual public ScribeIf {
 public:
  ScribeHandler() {
    // Your initialization goes here
  }

  ResultCode Log(const std::vector<LogEntry> & messages) {
    // Your implementation goes here
    printf("Log\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ScribeHandler> handler(new ScribeHandler());
  shared_ptr<TProcessor> processor(new ScribeProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

