/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "scribe_constants.h"

namespace rdd {

const scribeConstants g_scribe_constants;

scribeConstants::scribeConstants() {
}

} // namespace

