/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef scribe_CONSTANTS_H
#define scribe_CONSTANTS_H

#include "scribe_types.h"

namespace rdd {

class scribeConstants {
 public:
  scribeConstants();

};

extern const scribeConstants g_scribe_constants;

} // namespace

#endif
