/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Empty_constants.h"

namespace rdd { namespace empty {

const EmptyConstants g_Empty_constants;

EmptyConstants::EmptyConstants() {
}

}} // namespace

