/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Empty_CONSTANTS_H
#define Empty_CONSTANTS_H

#include "Empty_types.h"

namespace rdd { namespace empty {

class EmptyConstants {
 public:
  EmptyConstants();

};

extern const EmptyConstants g_Empty_constants;

}} // namespace

#endif
