/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Parallel_constants.h"

namespace rdd { namespace parallel {

const ParallelConstants g_Parallel_constants;

ParallelConstants::ParallelConstants() {
}

}} // namespace

