/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Parallel_CONSTANTS_H
#define Parallel_CONSTANTS_H

#include "Parallel_types.h"

namespace rdd { namespace parallel {

class ParallelConstants {
 public:
  ParallelConstants();

};

extern const ParallelConstants g_Parallel_constants;

}} // namespace

#endif
